### ISSUE TITLE
"factor" uses instead of "function" is Transform.r

### ISSUE THREAD

**Issue by BalintKomjati** [WonderAnn/bmarketing#1]
when i install the package 
devtools::install_github("WonderAnn/bmarketing")
i receive the following error
Error in parse(outFile) : 
     C:/Users/T440s/AppData/Local/Temp/RtmpoPIn15/Rbuild4c70dc7fb6/Team1/R/Transform.R:32:20: unexpected '{'
   31: 
   32: intonum<-factor(f) {
                          ^
   ERROR: unable to collate and parse R files for package 'Team1'

**Comment by WonderAnn** [comment]
Issue is fixed now.
