### ISSUE TITLE
can't install package - empty \TITLE{} in man/b.Rd  description file

### ISSUE THREAD

**Issue by zoltanszebenyi** [WonderAnn/bmarketing#2]
error message:

Error in Rd_info(db[[i]]) : 
     missing/empty \title field in '/tmp/Rtmpqxwyl0/Rbuild27c66181e2a/Team1/man/b.Rd'
   Rd files must have a non-empty \title.
See chapter 'Writing R documentation' in manual 'Writing R Extensions'.
─  removing ‘/tmp/Rtmpqxwyl0/Rinst27c5008c3da/Team1’
         -----------------------------------
   ERROR: package installation failed
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error

**Comment by zoltanszebenyi** [comment]
hi, now a new error message:

> devtools::install_github("WonderAnn/bmarketing")
Downloading GitHub repo WonderAnn/bmarketing@master
Skipping 1 packages not available: tidyverse    rpart
✔  checking for file ‘/tmp/Rtmpo3IqCP/remotes2af58a4271d/WonderAnn-bmarketing-1b070f8/DESCRIPTION’ ...
─  preparing ‘Team1’:
E  checking DESCRIPTION meta-information ...
   Malformed Depends or Suggests or Imports or Enhances field.
   Offending entries:
     tidyverse    rpart
   Entries must be names of packages optionally followed by '<=' or '>=',
   white space, and a valid version number in parentheses.
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
   
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error

**Comment by WonderAnn** [comment]
Fix applied. Package now installs. 
![image](https://user-images.githubusercontent.com/19766132/57444780-993bce00-7259-11e9-9783-e4606fd1afe8.png)
