### ISSUE TITLE
no package documentation available?

### ISSUE THREAD

**Issue by zoltanszebenyi** [WonderAnn/bmarketing#5]
> ?Team1
No documentation for ‘Team1’ in specified packages and libraries:
you could try ‘??Team1’

**Comment by NedelcuAlin** [comment]
Library updated, package documentation added

![Capture](https://user-images.githubusercontent.com/49719946/57447283-6d234b80-725f-11e9-8b77-71b0abf89794.PNG)

**Comment by zoltanszebenyi** [comment]
Hi, I reinstalled and resourced the package - but I still cant access the package docu:

> ?Team1
No documentation for ‘Team1’ in specified packages and libraries:
you could try ‘??Team1’


Can you call it with "?Team1"
