### ISSUE TITLE
functions not "@export"-ed

### ISSUE THREAD

**Issue by zoltanszebenyi** [WonderAnn/bmarketing#6]
The functions are only callable by calling "Team1:::" before them:

> library(Team1)
> clear1
Error: object 'clear1' not found
> Team1::clear1
Error: 'clear1' is not an exported object from 'namespace:Team1'
> Team1:::clear1
function (data) 
{
    newdata <- na.omit(data)
    if (nrow(newdata) == nrow(data)) {
        print("All okay: No Missing Value found")
    }
    else {
        print("Error: Missing Values found")
    }
}
<bytecode: 0x55d54c464128>
<environment: namespace:Team1>

**Comment by WonderAnn** [comment]
Export added for functions
![image](https://user-images.githubusercontent.com/19766132/57447444-c1c6c680-725f-11e9-9a89-bc968d95e87a.png)
